Node是为了解决编程模型中阻塞I/O的性能问题的，采用了单线程模型，这导致Node 更像一个处理I/O密集问题的能手，而CPU密集型则取决于管家的能耐如何

- 异常处理

不会catch的错误
Node.js原生提供uncaughtException事件挂到process对象上，用于捕获所有未处理的异常
```javascript
process.on('uncaughtException', function(err) {
    console.error('Error caught in uncaughtException event:', err);
});
 
try {
    process.nextTick(function() {
        fs.readFile('non_existent.js', function(err, str) {
            if(err) throw err;
            else console.log(str);
        });
    });
} catch(e) {
    console.error('Error caught by catch block:', e);
}
```
function的错误会进入uncaughtException中，但此时错误上下文已丢失，很难定位错误，而且一旦uncaughtException事件触发，整个node进程将crash掉，如果不做一些善后处理的话会导致整个服务挂掉

使用domain处理回调异常
```javascript
process.on('uncaughtException', function(err) {
    console.error('Error caught in uncaughtException event:', err);
});
 
var d = domain.create();
 
d.on('error', function(err) {
    console.error('Error caught by domain:', err);
});
 
d.run(function() {
    process.nextTick(function() {
        fs.readFile('non_existent.js', function(err, str) {
            if(err) throw err;
            else console.log(str);
        });
    });
});
```

promise,async/await同样无法处理回调的异常
```javascript
new Promise((resolve, reject) => {
    asyncError()
})
    .then(() => {
        //...
    })
    .catch((e) => {
        /*异常无法被捕获,导致进程退出*/
        console.log(e.message)
    })
```


co函数库
将yeild返回的value转为promise

koa通过promise处理

- 嵌套过深

- 无法进行代码阻塞

- 单线程，无法充分利用cpu(child_process)

- 原生不支持异步转同步


事件发布／订阅模式
